# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"(\n\x10OperationRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"#\n\x11OperationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x0c\n\nLogRequest\"\x19\n\x08LogEntry\x12\r\n\x05\x65ntry\x18\x01 \x01(\t2\x90\x01\n\x0f\x41\x64\x64itionService\x12\x42\n\x03\x41\x64\x64\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12\x39\n\x07GetLogs\x12\x16.calculator.LogRequest\x1a\x14.calculator.LogEntry0\x01\x32\x9b\x01\n\x15MultiplicationService\x12G\n\x08Multiply\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12\x39\n\x07GetLogs\x12\x16.calculator.LogRequest\x1a\x14.calculator.LogEntry0\x01\x42\x1a\n\x16\x63om.example.calculatorP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.example.calculatorP\001'
  _globals['_OPERATIONREQUEST']._serialized_start=32
  _globals['_OPERATIONREQUEST']._serialized_end=72
  _globals['_OPERATIONRESPONSE']._serialized_start=74
  _globals['_OPERATIONRESPONSE']._serialized_end=109
  _globals['_LOGREQUEST']._serialized_start=111
  _globals['_LOGREQUEST']._serialized_end=123
  _globals['_LOGENTRY']._serialized_start=125
  _globals['_LOGENTRY']._serialized_end=150
  _globals['_ADDITIONSERVICE']._serialized_start=153
  _globals['_ADDITIONSERVICE']._serialized_end=297
  _globals['_MULTIPLICATIONSERVICE']._serialized_start=300
  _globals['_MULTIPLICATIONSERVICE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
